### ISSUE TITLE
unreadable fonts for keys and values in Aptana NightLion

### ISSUE THREAD

**Issue by cfineman-sfdc** [boothen/Json-Eclipse-Plugin#18] opened 2018-04-22 21:10 UTC
I am using the Aptana NightLion color theme. I can barely read the key text (green) and the value text (dark blue) is pretty much unreadable. I can't find where your font colors are being set.

**Comment by cfineman-sfdc** [comment] 2018-04-23 20:38
@msteiger that worked well but I'm still puzzled why those dialogs didn't show up earlier (previously i was only able to choose a font). There was no formatter or color child of the JSON Editor node in preferences. FWIW I did install "web tools" after I removed this and did do some updates to eclipse:

Version: Oxygen.3a Release (4.7.3a)
Build id: 20180405-1200

**Comment by msteiger** [comment] 2018-04-26 18:38
Thanks for the update. I cannot reproduce the problem unfortunately. The original problem is solved, so I will close this.

If the preference page(s) disappear again, we can create a dedicated issue for that problem.

**Closed by msteiger** 2018-04-26 18:38 UTC
